### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/dev/stdout'

### ISSUE THREAD

**Issue by msenol86** [thaJeztah/pgadmin4-docker#11]
I get this error on Ubuntu 14.04. I tried both sudo and without sudo

**Comment by thaJeztah** [comment]
@msenol86 What options did you use to start the container? Can you show the exact command you used?

**Comment by klshxsh** [comment]
I just had the same problem running on a CentOS 6.7 host, with the the following docker version:

```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

In case this helps anyone, I was able to work around the problem by starting the docker container like this:

```
docker run -d -p 5050:5050 --name pgadmin thajeztah/pgadmin4 \
  sh -c "python /usr/local/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py > /dev/null 2>&1"
```

i.e. Redirecting all output to /dev/null

**Comment by thaJeztah** [comment]
Closing this issue, because I'm not able to reproduce

@klshxsh I'd really recommend upgrading your host OS; CentOS 6 has not been supported by Docker for a long time, and Docker 1.7.1 is no longer maintained, and has known vulnerabilities.
