### ISSUE TITLE
Inclusion of postgresql in image

### ISSUE THREAD

**Issue by HUSSTECH** [thaJeztah/pgadmin4-docker#17]
First, thanks for this repo and Dockerfile. Super useful.

Just wanted to ask if it was an intentional choice to not include a `postgresql` installation with this image. I wanted to have this so that the `pg_dump` and `pg_restore` binaries are available to be able to run those commands from pgadmin4. I have just added on my local repo and it builds/works fine by filling in the binary paths in the app settings.

Also, the current version of alpine that this image is based on only has a postgres 9.5 compatible `postgresql` package in its repo. Whereas `python:2-alpine3.6` has the pg9.6 package. The latest release.

I'm happy to make a PR with the changes and update the README accordingly. But I also understand if the intention was to keep the image small and minimal.

**Comment by evertonpaiva** [comment]
+1

It would be great! Maybe the user could choose wich pgclient version through env variables.

**Comment by thaJeztah** [comment]
I just made a change to include those tools in the image; I'll be bumping the version to pgAdmin 2.0, which will include that change; https://github.com/thaJeztah/pgadmin4-docker/pull/23
