### ISSUE TITLE
separate doc for more standard setup

### ISSUE THREAD

**Issue by babatundebusari** [thaJeztah/pgadmin4-docker#2]
I see you ran `docker network create...`
but this is not standard way people run docker containers

Any way of adding a typical/standard `docker run ...` command for simplicity?

**Comment by thaJeztah** [comment]
> but this is not standard way people run docker containers

It _should_ be standard practice; docker networks are used to allow containers to communicate with each other, without leaving the private network of docker.

I added a simple "quickstart" example to see the image in action; https://github.com/thaJeztah/pgadmin4-docker/commit/4d57a77029b0a982a6cd30ac73694e3cd80dba6a

I'll close this issue, but let me know if you have additional suggestions. Thanks for opening this issue (and sorry for the delay :smile:)
