### ISSUE TITLE
Configure connection on startup

### ISSUE THREAD

**Issue by aleogr** [thaJeztah/pgadmin4-docker#26]
Good morning.

I was wondering if is it possible somehow to automatically configure a connection to a database on pgadmin startup.

Thanks.

**Comment by thaJeztah** [comment]
I don't think pgAdmin has this option to easily configure this from the command-line. The configuration (including servers that are configured) is stored in a SQLite database, located at `/pgadmin/config/pgadmin4.db` inside the container. That directory is defined as a volume, so the configuration will persist in a volume after the container was deleted, so you can either pass a custom volume that contains an existing configuration database, or bind-mount one from the host, e.g.;

```
docker run -d -p 5050:5050 \
  --name=pgadmin \
  --network=pg \
  --volume=myvolume-with-configuration:/pgadmin/config/ \
  thajeztah/pgadmin4
```

or if you have a `pgadmin4.db` file on your host in (e.g.) a directory `/users/me/pgadmin-config`;


```
docker run -d -p 5050:5050 \
  --name=pgadmin \
  --network=pg \
  --volume=/users/me/pgadmin-config/:/pgadmin/config/ \
  thajeztah/pgadmin4
```
