### ISSUE TITLE
[Noob Question] - Which host do you use inside pgAdmin to connect to the DP? (in your 'Practical example')

### ISSUE THREAD

**Issue by JasoonS** [thaJeztah/pgadmin4-docker#29]
I wasn't able to connect to the database when specifying the `host` as `localhost` or `0.0.0.0`. What value to you put in that field?

I was able to get everything to work if I used `--net="host"`, however. But no luck with `--net pg` as in your instructions from 'Practical example'

I'm not sure if this is the same issue as is spoken about here: #12 ?

But thanks for sharing this, super useful :+1:

**Comment by thaJeztah** [comment]
When using the `--net=pg` in the example, you're connecting to the database over the container-container network. In those networks, you can connect to other containers using their _name_ as hostname (so `postgres` in the example, which is the container-name)

**Comment by JasoonS** [comment]
Thanks, working 100%

**Comment by thaJeztah** [comment]
Great!
